Set up CI with Azure Pipelines
rtaum/CustomerApi pull request #2
Opened 2018-12-05 13:45 UTC by rtaum

2018-12-27 17:02 UTC, rtaum commented
Hey

2018-12-27 20:45 UTC, rtaum commented
Test

2018-12-27 20:55 UTC, artot-1 requested changes
Do something

2018-12-28 17:14 UTC, artot-1 approved these changes

2018-12-28 17:15 UTC, artot-1 approved these changes

2018-12-28 17:16 UTC, closed without merging